wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1636498546
    t:
      3:
      - 16
      4: 3.8.10
      5: 0.12.6
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: golden_abbr.csv
learning_rate:
  desc: null
  value: 0.02
